<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>AutoCAD二次开发基本操作命令 - IT学习者博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="AutoCAD二次开发基本操作命令" />
<meta property="og:description" content="刚接触auto CAD二次开发不久，对这个行业了解还很少，写一些东西，为了记录一下自己的成长历程。刚开始来到公司时，就是要学习AutoCAD ObjectARX这本书，对于一个初学者来说，自己看书还是挺费劲的，所以我就看着书上的代码，在visual studio上敲出来试着运行调试一下。可是我发现，不一定能运行出来，因为每个电脑设置的内部环境不同，所以对于相同的一套代码，不一定能在两台电脑上运行出来，所以需要我们做的是，了解自己用的这个电脑的内部环境，然后将代码改成能适应我们内部环境的代码即可。我刚开始时就会画一些简单的直线、圆、弧线，虽然不是很难，但是画出来之后有一种小小的成就感。我对CAD的这些代码理解的还很浅显，所以我将他记录下来，以便日后更深入理解。如下所列出的几个命令是建立在基类都已经创建好的基础上的，如有错误，欢迎广大读者指正。
“创建一条直线”命令
void createline（） { AcGePoint3d ptStart(0,0,0); AcGePoint3d ptEnd(100,100,0); AcDbLine *pLine = new AcDbLine(ptStart,ptEnd); CQhDwg::AddEntity(pLine,_T(&#34;&#34;)); //以上代码可画出一条线，以下代码也可，下面的更简单 CQhDwg::AddLine(AcGePoint3d(1000,0,0),AcGePoint3d(5000,0,0),_T(&#34;&#34;)); } “创建多段线”命令
CQhCfg.cpp AcDbObjectId CQhDwg::AddPoLyLine(const AcGePoint3dArray&amp; aryPts,double dWidth,bool bClose/*=true*/,CString strLayer/*=_T*/,AcDbDatabase* pDb/*=NULL*/) { AcDbPolyline* pLy=new AcDbPolyline; for (int i=0;i&lt;aryPts.length();&#43;&#43;i) { pLy-&gt;addVertexAt(i,CQhDwg::pt3dto2d(aryPts[i])); pLy-&gt;setWidthsAt(i,dWidth,dWidth); } pLy-&gt;setClosed(bClose); pLy-&gt;setLayer(strLayer); return AddEntity(pLy,strLayer); } ZhidanArchCADCommands.cpp AcGePoint3dArray ary; ary.append(AcGePoint3d(200,400,0)); ary.append(AcGePoint3d(500,300,0)); ary.append(AcGePoint3d(600,700,0)); CQhDwg::AddPoLyLine(ary,1); “画弧线”命令
AcDbObjectId CQhDwg::AddArc(const AcGePoint3d &amp;ptCenter,double radius,double startAngle,double endAngle,CString strLayer/*=_T*/,AcDbDatabase* pDb/*=NULL*/) { AcGeVector3d vec(0,0,1); AcDbArc *pArc = new AcDbArc(ptCenter,vec,radius,startAngle,endAngle); return AddEntity(pArc); } “画圆”命令" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://itnewbiea.github.io/posts/a0e35aa054a80af164aeed9e9944846f/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2019-07-10T14:45:57+08:00" />
<meta property="article:modified_time" content="2019-07-10T14:45:57+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="IT学习者博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">IT学习者博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">AutoCAD二次开发基本操作命令</h1>
			
		</header>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>刚接触auto CAD二次开发不久，对这个行业了解还很少，写一些东西，为了记录一下自己的成长历程。刚开始来到公司时，就是要学习AutoCAD ObjectARX这本书，对于一个初学者来说，自己看书还是挺费劲的，所以我就看着书上的代码，在visual studio上敲出来试着运行调试一下。可是我发现，不一定能运行出来，因为每个电脑设置的内部环境不同，所以对于相同的一套代码，不一定能在两台电脑上运行出来，所以需要我们做的是，了解自己用的这个电脑的内部环境，然后将代码改成能适应我们内部环境的代码即可。我刚开始时就会画一些简单的直线、圆、弧线，虽然不是很难，但是画出来之后有一种小小的成就感。我对CAD的这些代码理解的还很浅显，所以我将他记录下来，以便日后更深入理解。如下所列出的几个命令是建立在基类都已经创建好的基础上的，如有错误，欢迎广大读者指正。</p> 
<p>“创建一条直线”命令</p> 
<pre class="has"><code class="language-cpp">void  createline（）
{
                AcGePoint3d ptStart(0,0,0);
	AcGePoint3d ptEnd(100,100,0);
	AcDbLine *pLine = new AcDbLine(ptStart,ptEnd);
	CQhDwg::AddEntity(pLine,_T(""));
                
                 //以上代码可画出一条线，以下代码也可，下面的更简单
	 CQhDwg::AddLine(AcGePoint3d(1000,0,0),AcGePoint3d(5000,0,0),_T(""));
}</code></pre> 
<p> “创建多段线”命令</p> 
<pre class="has"><code class="language-cpp">CQhCfg.cpp

AcDbObjectId CQhDwg::AddPoLyLine(const AcGePoint3dArray&amp; aryPts,double dWidth,bool bClose/*=true*/,CString strLayer/*=_T*/,AcDbDatabase* pDb/*=NULL*/)
{
	AcDbPolyline* pLy=new AcDbPolyline;
	for (int i=0;i&lt;aryPts.length();++i)
	{
		pLy-&gt;addVertexAt(i,CQhDwg::pt3dto2d(aryPts[i]));
		pLy-&gt;setWidthsAt(i,dWidth,dWidth);
	}
	pLy-&gt;setClosed(bClose);
	pLy-&gt;setLayer(strLayer);
	return AddEntity(pLy,strLayer);
}


ZhidanArchCADCommands.cpp
AcGePoint3dArray ary;
	ary.append(AcGePoint3d(200,400,0));
	ary.append(AcGePoint3d(500,300,0));
	ary.append(AcGePoint3d(600,700,0));
	CQhDwg::AddPoLyLine(ary,1);</code></pre> 
<p> “画弧线”命令</p> 
<pre class="has"><code class="language-cpp">AcDbObjectId CQhDwg::AddArc(const AcGePoint3d &amp;ptCenter,double radius,double startAngle,double endAngle,CString strLayer/*=_T*/,AcDbDatabase* pDb/*=NULL*/)
{
	AcGeVector3d vec(0,0,1);
	AcDbArc *pArc = new AcDbArc(ptCenter,vec,radius,startAngle,endAngle);
	return AddEntity(pArc);
}</code></pre> 
<p>“画圆”命令</p> 
<pre class="has"><code class="language-cpp">AcDbObjectId  CQhDwg::AddCircle(const AcGePoint3d &amp;centerPoint,double radius)
{
	AcGeVector3d normal(0,0,1);//确定圆的法向量，也可放到函数变量中；
	AcDbCircle *pCircle = new AcDbCircle(centerPoint,normal,radius);
	return AddEntity(pCircle);
}</code></pre> 
<p> “填充”命令</p> 
<pre class="has"><code class="language-cpp">CQhCfg.cpp

AcDbObjectId CQhDwg::AddHatch(const AcDbObjectIdArray&amp; aryExtIds,CString strHatch,double dSc,CString strLayer/*=_T("")*/,AcDbDatabase* pDb/* =NULL */)
{
	AcDbHatch* pHatch=new AcDbHatch;
	pHatch-&gt;setElevation(0);
	pHatch-&gt;setPatternAngle(0);
	pHatch-&gt;setPatternScale(dSc);
	pHatch-&gt;setAssociative(Adesk::kFalse);
	pHatch-&gt;setHatchStyle(AcDbHatch::kNormal);
	pHatch-&gt;appendLoop(AcDbHatch::kExternal,aryExtIds);
	pHatch-&gt;setPattern(AcDbHatch::kPreDefined,strHatch);
	pHatch-&gt;evaluateHatch();

	return AddEntity(pHatch,strLayer);
}

ZhidanArchCADCommands.cpp

AcDbObjectIdArray ary1;
                AcDbObjectId id = CQhDwg::AddLine(AcGePoint3d(0,0,0),AcGePoint3d(100,100,0),_T(""));	
                AcDbObjectId id1 = CQhDwg::AddLine(AcGePoint3d(0,0,0),AcGePoint3d(200,0,0),_T(""));
	AcDbObjectId id2 = CQhDwg::AddLine(AcGePoint3d(100,100,0),AcGePoint3d(200,0,0),_T(""));
	ary1.append(id);
	ary1.append(id1);
	ary1.append(id2);
    CQhDwg::AddHatch(ary1,"人工草地",1);
</code></pre> 
<p> </p> 
<p> “写文字”命令</p> 
<pre class="has"><code class="language-cpp">AcDbObjectId CQhDwg::AddText(AcGePoint3d pt,const TCHAR* text,TextInfo info,double dAngle,AcDb::TextHorzMode horzmode,AcDb::TextVertMode vertmode,CString strLayer/*=_T("")*/,AcDbDatabase* pDb/* =NULL */)
{
	AcDbText* pText=new AcDbText;
	pText-&gt;setLayer(strLayer);
	pText-&gt;setTextString(text);
	pText-&gt;setHeight(info.dTextHigh);
	pText-&gt;setWidthFactor(info.dTextWidthFactor);
	pText-&gt;setTextStyle(info.idStyle);
	pText-&gt;setRotation(dAngle);
	pText-&gt;setHorizontalMode(horzmode);
	pText-&gt;setVerticalMode(vertmode);
//	pText-&gt;setPosition(pt);
	pText-&gt;setAlignmentPoint(pt);

	return AddEntity(pText,strLayer,pDb);
}
ZhidanArchCADCommands.cpp
CQhDwg::AddText(AcGePoint3d(3000,3000,3000),_T("输入你要写的文字"), info,0.5,AcDb::kTextMid,AcDb::kTextVertMid);</code></pre> 
<p>“修改线的颜色”命令</p> 
<pre class="has"><code class="language-cpp">void change color()
{
                AcGePoint3d ptStart(0,0,0);
	AcGePoint3d ptEnd(100,100,0);
	AcDbLine *pLine = new AcDbLine(ptStart,ptEnd);
	AcDbObjectId id = CQhDwg::AddEntity(pLine,_T(""));
                CQhDwg::setColor( id, 1);
}</code></pre> 
<p>“选择对象”命令</p> 
<pre class="has"><code class="language-cpp">ads_name ssname;
	ads_point pt1,pt2;
	pt1[X] = pt1[Y] = pt1[Z] = 0;
	pt2[X] = pt2[Y] = 100;
	pt2[Z] = 0;
    //选择图形中与pt1和pt2组成的窗口相交的所有对象
	acedSSGet(_T("C"),pt1,pt2,NULL,ssname);
	long length;
	acedSSLength(ssname,&amp;length);
	acutPrintf(_T("\n实体数:%d"));
	acedSSFree(ssname);</code></pre> 
<p> </p>
                </div>
		</div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/a2e82680aa14d8d025ffcf295d216289/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/d66f42ade98e9babf6493226a3dc0112/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">IAI OpenLab工业人工智能开放实验室白皮书（一）</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 IT学习者博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<script src="https://itnewbiea.github.io/js/foot.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>