<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>【图形-OpenCascade】OpenCascade使用 - IT学习者博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="【图形-OpenCascade】OpenCascade使用" />
<meta property="og:description" content="GeomConvert------- BSpline曲线、曲面拆分，Handle(Geom_Curve)转BSpline曲线
BRepExtrema_DistShapeShape------求两个TopoDS_Shape（TopoDS_Face、TopoDS_Vertex、TopoDS_Edge、TopoDS_Wire...）的最近距离，得到这个距离所对应的点【在TopoDS_Shape1上的和TopoDS_Shape2上的都可以得到】、最近距离的值、最近距离点的个数
GeomAPI_IntCS----求Geom_Curve和Geom_Surface的交点、交点，得到交点的个数和对应的交点、曲线段的条数、对应的曲线（Geom_Curve）
GeomAPI_IntSS----求Geom_Surface和Geom_Surface的交线，得到交线的条数和对应的交线
BRepAlgoAPI_Section---求TopoDS_Shape和TopoDS_Shape、Geom_Surface和TopoDS_Shape、TopoDS_Shape和gp_Pln相交后的数据，得到TopoDS_Shape【包含相交部分的数据，BRepAlgoAPI_Section继承于BRepBuilderAPI_MakeShape】
BRep_Tool---TopoDS_Face转Geom_Surface、TopoDS_Edge转Geom_Curve（转完后可以得到曲线U值范围）、TopoDS_Vertex转gp_Pnt
StlTransfer---TopoDS_Shape转StlMesh_Mesh
StlMesh_MeshExplorer---StlMesh_Mesh的遍历器、获得三角面片的三个顶点的x、y、z值
遍历示例：
TopoDS_Shape TrimNurbsToSTL( const TopoDS_Face&amp; aTrimTopFace,Standard_Real precision ) { TopoDS_Face TopoFace = BRepBuilderAPI_MakeFace(aTrimTopFace).Face(); Handle_StlMesh_Mesh aSTLMesh = new StlMesh_Mesh(); StlTransfer::BuildIncrementalMesh(TopoFace, precision, Standard_False, aSTLMesh); Standard_Integer NumberDomains = aSTLMesh-&gt;NbDomains(); Standard_Integer iND; gp_XYZ p1, p2, p3; TopoDS_Vertex Vertex1, Vertex2, Vertex3; TopoDS_Face AktFace; TopoDS_Wire AktWire; BRepBuilderAPI_Sewing aSewingTool; Standard_Real x1, y1, z1; Standard_Real x2, y2, z2; Standard_Real x3, y3, z3; aSewingTool.Init(CAD_NURBS_STL_TOLERANCE,Standard_True); TopoDS_Compound aComp; BRep_Builder BuildTool; BuildTool.MakeCompound( aComp ); StlMesh_MeshExplorer aMExp (aSTLMesh); for (iND=1;iND&lt;=NumberDomains;iND&#43;&#43;) { for (aMExp." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://itnewbiea.github.io/posts/028e8493c136a5d275e84bcd1e392f21/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2013-03-18T17:20:58+08:00" />
<meta property="article:modified_time" content="2013-03-18T17:20:58+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="IT学习者博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">IT学习者博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">【图形-OpenCascade】OpenCascade使用</h1>
			
		</header>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p><span style="color:#339999">GeomConvert</span>-------  BSpline曲线、曲面拆分，Handle(Geom_Curve)转BSpline曲线</p> 
<p><span style="color:#339999"><span style="background-color:rgb(255,255,255)">BRepExtrema_DistShapeShape</span><span style="background-color:rgb(255,255,255)"></span></span>------求两个TopoDS_Shape（TopoDS_Face、TopoDS_Vertex、TopoDS_Edge、TopoDS_Wire...）的最近距离，得到这个距离所对应的点【在TopoDS_Shape1上的和TopoDS_Shape2上的都可以得到】、最近距离的值、最近距离点的个数<br> </p> 
<p><span style="color:#339999; background-color:rgb(255,255,255)">GeomAPI_IntCS</span>----求Geom_Curve和Geom_Surface的交点、交点，得到交点的个数和对应的交点、曲线段的条数、对应的曲线（Geom_Curve）<br> </p> 
<p><span style="color:#339999; background-color:rgb(255,255,255)">GeomAPI_IntSS</span>----求Geom_Surface和Geom_Surface的交线，得到交线的条数和对应的交线<br> </p> 
<p><span style="color:#339999">BRepAlgoAPI_Section</span>---求TopoDS_Shape和TopoDS_Shape、Geom_Surface和TopoDS_Shape、TopoDS_Shape和gp_Pln相交后的数据，得到TopoDS_Shape【包含相交部分的数据，BRepAlgoAPI_Section继承于BRepBuilderAPI_MakeShape】</p> 
<p><span style="color:#339999">BRep_Tool</span>---TopoDS_Face转Geom_Surface、TopoDS_Edge转Geom_Curve（转完后可以得到曲线U值范围）、TopoDS_Vertex转gp_Pnt<br> </p> 
<p><span style="color:#339999">StlTransfer</span>---TopoDS_Shape转StlMesh_Mesh<br> </p> 
<p><span style="color:#339999">StlMesh_MeshExplorer</span>---StlMesh_Mesh的遍历器、获得三角面片的三个顶点的x、y、z值</p> 
<p>遍历示例：</p> 
<p></p> 
<pre><code class="language-cpp"> TopoDS_Shape TrimNurbsToSTL( const TopoDS_Face&amp; aTrimTopFace,Standard_Real precision )
 {
	 TopoDS_Face TopoFace = BRepBuilderAPI_MakeFace(aTrimTopFace).Face();
	 Handle_StlMesh_Mesh aSTLMesh = new StlMesh_Mesh();
	 StlTransfer::BuildIncrementalMesh(TopoFace, precision, Standard_False, aSTLMesh);

	 Standard_Integer NumberDomains = aSTLMesh-&gt;NbDomains();
	 Standard_Integer iND;
	 gp_XYZ p1, p2, p3;
	 TopoDS_Vertex Vertex1, Vertex2, Vertex3;
	 TopoDS_Face AktFace;
	 TopoDS_Wire AktWire;
	 BRepBuilderAPI_Sewing aSewingTool;
	 Standard_Real x1, y1, z1;
	 Standard_Real x2, y2, z2;
	 Standard_Real x3, y3, z3;

	 aSewingTool.Init(CAD_NURBS_STL_TOLERANCE,Standard_True);

	 TopoDS_Compound aComp;
	 BRep_Builder BuildTool;
	 BuildTool.MakeCompound( aComp );

	 StlMesh_MeshExplorer aMExp (aSTLMesh);

	 for (iND=1;iND&lt;=NumberDomains;iND++) 
	 {
		 for (aMExp.InitTriangle (iND); aMExp.MoreTriangle (); aMExp.NextTriangle ()) 
		 {
			 aMExp.TriangleVertices (x1,y1,z1,x2,y2,z2,x3,y3,z3);
			 p1.SetCoord(x1,y1,z1);
			 p2.SetCoord(x2,y2,z2);
			 p3.SetCoord(x3,y3,z3);

			 if ((!(p1.IsEqual(p2,0.0))) &amp;&amp; (!(p1.IsEqual(p3,0.0))))
			 {
				 Vertex1 = BRepBuilderAPI_MakeVertex(p1);
				 Vertex2 = BRepBuilderAPI_MakeVertex(p2);
				 Vertex3 = BRepBuilderAPI_MakeVertex(p3);

				 AktWire = BRepBuilderAPI_MakePolygon( Vertex1, Vertex2, Vertex3, Standard_True);

				 if( !AktWire.IsNull())
				 {
					 AktFace = BRepBuilderAPI_MakeFace( AktWire);
					 if(!AktFace.IsNull())
						 BuildTool.Add( aComp, AktFace );
				 }
			 }
		 }
	 }
	 aSTLMesh-&gt;Clear();

	 aSewingTool.Load( aComp );
	 aSewingTool.Perform();
	 TopoDS_Shape aShape = aSewingTool.SewedShape();
	 if ( aShape.IsNull() )
		 aShape = aComp;

	 return aShape;

	
 }</code></pre> 
<br> 
<p></p> 
<p><span style="color:#339999">StlMesh_Mesh</span>---获得网格片数、网格面片中的三角面片个数</p> 
<p><span style="color:#339999">TopoDS_Shape</span>---存储数据的拓扑结构<br> </p> 
<p><span style="color:#339999">TopExp_Explorer</span>---TopoDS_Shape的遍历器<br> </p> 
<p>遍历示例;</p> 
<p></p> 
<pre><code class="language-cpp">void example()
{
	TopoDS_Shape aShape;
	TopoDS_Face aFace;
	TopoDS_Wire aWire;
	TopoDS_Edge aEdge;
	TopoDS_Vertex aVertex;
	TopExp_Explorer Exp_Edge;
	TopExp_Explorer Exp_Wire;
	TopExp_Explorer Exp_Face;
	TopExp_Explorer Exp_Vertex;
	for (Exp_Face.Init(aShape,TopAbs_FACE);Exp_Face.More();Exp_Face.Next())
	{
		aFace = TopoDS::Face(Exp_Face.Current());
		for (Exp_Wire.Init(aFace,TopAbs_WIRE);Exp_Wire.More();Exp_Wire.Next())
		{
			aWire = TopoDS::Wire(Exp_Wire.Current());
			for (Exp_Edge.Init(aWire,TopAbs_EDGE);Exp_Edge.More();Exp_Edge.Next())
			{
				aEdge = TopoDS::Edge(Exp_Edge.Current());
				for (Exp_Vertex.Init(aEdge,TopAbs_VERTEX);Exp_Vertex.More();Exp_Vertex.Next())
				{
					aVertex = TopoDS::Vertex(Exp_Vertex.Current());
					gp_Pnt Pnt = BRep_Tool::Pnt(aVertex);
				}
			}
		}
	}
	for (Exp_Vertex.Init(aShape,TopAbs_VERTEX);Exp_Vertex.More();Exp_Vertex.Next())
	{
		aVertex = TopoDS::Vertex(Exp_Vertex.Current());
		gp_Pnt Pnt = BRep_Tool::Pnt(aVertex);
	}
	for (Exp_Edge.Init(aShape,TopAbs_EDGE);Exp_Edge.More();Exp_Edge.Next())
	{
		aEdge = TopoDS::Edge(Exp_Edge.Current());
		Standard_Real First,Last;
		Handle(Geom_Curve) Pnt = BRep_Tool::Curve(aEdge,First,Last);
	}
	for (Exp_Wire.Init(aShape,TopAbs_WIRE);Exp_Wire.More();Exp_Wire.Next())
	{
		aWire = TopoDS::Wire(Exp_Wire.Current());
	}
	for (Exp_Face.Init(aShape,TopAbs_WIRE);Exp_Face.More();Exp_Face.Next())
	{

		aFace = TopoDS::Face(Exp_Face.Current());
		 Handle(Geom_Surface) aSurface = BRep_Tool::Surface(aFace);
	}
}</code></pre>拓扑创建： 
<p></p> 
<p></p> 
<pre><code class="language-cpp">BRepBuilderAPI_MakeVertex = TopoDS_Vertex
BRepBuilderAPI_MakeEdge = TopoDS_Edge
BRepBuilderAPI_MakeWire = TopoDS_Wire
BRepBuilderAPI_MakeFace = TopoDS_Face
BRepBuilderAPI_MakePolygon = TopoDS_Wire //直线框</code></pre> 
<br> 几何容器：数组队列 
<p></p> 
<p>TColGeom_xxxxxxxxxxxxxxxxxx</p> 
<p>TColgp_xxxxxxxxxxxxxxxxxxxxxx<br> </p> 
<p>TColStd_xxxxxxxxxxxxxxxxxxxxx<br> </p> 
<p>TDataStd_xxxxxxxxxxxxxxxxxxx</p> 
<p><br> <br> </p> 
<p><br> </p>
                </div>
		</div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/481f338a7916e9e18b19683a746c1023/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">多长时间可以成长为一个架构师？</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/092da09417cb4c4d3e4e1748c0b8798a/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">黑盒测试、白盒测试、单元测试、集成测试、系统测试、验收测试的区别与联系...</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 IT学习者博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<script src="https://itnewbiea.github.io/js/foot.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>